<%
String sPACTL_DEVICE = "";
String sPACTL_SINK_DEVICE = "0";
String sPACTL_SINK_DEVICE_CHANNEL_TO_GET_VOLUME = "front-left";
String sPACTL_SOURCE_DEVICE = "";

int nMAX_ALLOWED_VOLUME_TO_ADJUST = 100;	//
int nMIN_ALLOWED_VOLUME_TO_ADJUST = 50;	//
int nVOLUME_ADJUST_STEP = 5;	//

boolean bALLOW_ADJUST_VOLUME_WHEN_WEARING_EARPHONE = false;

boolean bPLAY_BAIDU_TTS_WHEN_ADJUSTING_VOLUME = true;
String sBAIDU_TTS_APPID = "";
String sBAIDU_TTS_KEY = "";
%>
